// imports/ui/components/app/App.tsx
// imports
import Top from '../header/Top';
import Navigation from '../header/Navigation';
import Routing from '../routing/Routing';
import Colofon from '../footer/Colofon';
import Consent from '../footer/Consent';
import { consentFooterVisible } from '../../stores/utils';

// Routing: Main content, based on chosen routes
export default function App() {
  // functions
  function toggleFooterConsentVisibility() {
    consentFooterVisible.set(!consentFooterVisible());
  }

  return (
    <>
      <header>
        <Top />
        <Navigation />
      </header>
      <main>
        <Routing />
      </main>
      <footer>
        <Colofon onClick={toggleFooterConsentVisibility} />
        <Consent />
      </footer>
    </>
  );
}

// client/App.svelte
<script>
  // packages

  // components
  import Header from '../imports/ui/header/Header.svelte';
  import Navigation from '../imports/ui/header/Navigation.svelte';
  import Main from '../imports/ui/main/Main.svelte';
  import Routing from '../imports/ui/routing/Routing.svelte';
  import Footer from '../imports/ui/footer/Footer.svelte';
  import FooterContent from '../imports/ui/footer/FooterContent.svelte';

  // variables
  import {language} from './stores';

  // components
</script>

<Header>
  <Navigation />
</Header>
<Main>
  <Routing />
</Main>
<Footer>
  <FooterContent />
</Footer>
