// imports/ui/components/consultancy/home/Consultancy.tsx
import {For, createMemo} from 'solid-js';
import BreadCrumbs from '../../reusable/BreadCrumbs';
import CardCopy from '../../reusable/CardCopy';
import {language} from '../../../stores/utils';
import {consultancyHomeItems} from '../../../stores/consultancy';
import createConverter from '/imports/ui/functions/convert';

export default function Consultancy() {
  const converter = createConverter();
  
  const expandedConsultancyHomeItems = createMemo(() =>
    converter.expandItems(consultancyHomeItems(), language())
  );

  return (
    <>
      <BreadCrumbs />
      <section>
        <div class="home__flex">
          <For each={expandedConsultancyHomeItems()}>
            {(item) => (
              <CardCopy backgroundColor={'--var'} color={'blue'} fontSize={'0.9em'}>
                {(C) => (
                  <>
                    <C.Title>{item.displayName}</C.Title>
                    <C.Body innerHTML={item.description} />
                    <C.Action link={item.link}>{item.action}</C.Action>
                  </>
                )}
              </CardCopy>
            )}
          </For>
        </div>
        <style>{`
  .home__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2em;
  }

  .home__flex .card {
    flex: 1 1 32rem;
  }
        `}</style>
      </section>
    </>
  );
}

// imports/ui/components/consultancy/home/Consultancy.svelte
<script lang="ts">
  // imports
  import BreadCrumbs from '../../reusable/BreadCrumbs.svelte';
  import CardCopy from '../../reusable/CardCopy.svelte';

  import {language} from '../../../stores/utils';
  import {consultancyHomeItems} from '../../../stores/consultancy';
  import createConverter from '/imports/ui/functions/convert';

  // variables
  const converter = createConverter();
  $: expandedConsultancyHomeItems = converter.expandItems<
    (typeof $consultancyHomeItems)[number],
    (typeof $consultancyHomeItems)[number]['definitions'][0]
  >($consultancyHomeItems, $language);
</script>

<BreadCrumbs />
<section>
  <div class="home__flex">
    {#each expandedConsultancyHomeItems as item}
      <CardCopy let:C backgroundColor={'--var'} color={'blue'} fontSize={'0.9em'}>
        <C.Title>{item.displayName}</C.Title>
        <!-- @html because of <mark></mark> tags in text -->
        <C.Body>{@html item.description}</C.Body>
        <C.Action link={item.link}>{item.action}</C.Action>
      </CardCopy>
    {/each}
  </div>
</section>

<style>
  .home__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2em;
  }

  .home__flex :global(.card) {
    flex: 1 1 32rem;
  }
</style>
