// imports/ui/components/app/App.tsx
// imports
import Top from '../header/Top';
import Navigation from '../header/Navigation';
import Routing from '../routing/Routing';
import Colofon from '../footer/Colofon';
import Consent from '../footer/Consent';
import { consentFooterVisible } from '../../stores/utils';

// Routing: Main content, based on chosen routes
export default function App() {
  // functions
  function toggleFooterConsentVisibility() {
    consentFooterVisible.set(!consentFooterVisible());
  }

  return (
    <>
      <header>
        <Top />
        <Navigation />
      </header>
      <main>
        <Routing />
      </main>
      <footer>
        <Colofon onClick={toggleFooterConsentVisibility} />
        <Consent />
      </footer>
    </>
  );
}

// imports/ui/components/app/App.svelte
<script lang="ts">
  // imports
  import Top from '../header/Top.svelte';
  import Navigation from '../header/Navigation.svelte';
  import Routing from '../routing/Routing.svelte';
  import Colofon from '../footer/Colofon.svelte';
  import Consent from '../footer/Consent.svelte';
  import {consentFooterVisible} from '../../stores/utils';

  // variables

  // functions
  function toggleFooterConsentVisibility() {
    $consentFooterVisible = $consentFooterVisible === false ? true : $consentFooterVisible === true ? false : true;
  }
</script>

<!-- Routing: Main content, based on chosen routes   -->
<header>
  <Top />
  <Navigation />
</header>
<main>
  <Routing />
</main>
<footer>
  <Colofon on:click={toggleFooterConsentVisibility} />
  <Consent />
</footer>
