// imports/ui/components/header/Navigation.tsx
// imports
import { createSignal, createEffect, Show } from 'solid-js';
import { useLocation, A } from '@solidjs/router';
import { language, isSmallScreen, navigationVisible, useMediaQuery } from '../../stores/utils';

export default function Navigation() {
  const location = useLocation();

  // Setup media query subscription
  createEffect(() => {
    const mediaQuery = useMediaQuery('(max-width: 768px)');
    createEffect(() => {
      isSmallScreen.set(mediaQuery());
    });
  });

  createEffect(() => {
    navigationVisible.set(isSmallScreen() ? false : true);
  });

  const handleClick = () => {
    if (isSmallScreen()) {
      navigationVisible.set(false);
    } else {
      navigationVisible.set(true);
    }
  };

  return (
    <>
      <Show when={navigationVisible()}>
        <nav class="key" style="transition: all 0.3s ease-in-out">
          <ul>
            <li>
              <A
                href="/"
                end
                class="brand"
                onClick={handleClick}
              >
                <span class="blue">Comms</span>
                &nbsp;
                <span class="green">With&nbsp;A</span>
                &nbsp;
                <span class="red">Plan</span>
              </A>
            </li>
            <li>
              <A href="/consultancy">
                <span class="blue">{language() === 'nl-NL' ? 'Consultancy' : 'Consultancy'}</span>
              </A>
            </li>
            <li>
              <A href="/tools">
                <span class="blue">{language() === 'nl-NL' ? 'Tools' : 'Tools'}</span>
              </A>
            </li>
          </ul>
        </nav>
      </Show>

      <Show when={location.pathname === '/' && navigationVisible()}>
        <nav class="sub" style="transition: all 0.3s ease-in-out">
          <ul>
            <li>
              <A href="/" onClick={handleClick}>
                <span>Home</span>
              </A>
            </li>
          </ul>
        </nav>
      </Show>

      <Show when={location.pathname.startsWith('/consultancy') && navigationVisible()}>
        <nav class="sub" style="transition: all 0.3s ease-in-out">
          <ul>
            <li>
              <A href="/consultancy" end onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Home' : 'Home'}</span>
              </A>
            </li>
            <li>
              <A href="/consultancy/work" onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Werk' : 'Work'}</span>
              </A>
            </li>
            <li>
              <A href="/consultancy/about" onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Over' : 'About'}</span>
              </A>
            </li>
            <li>
              <A href="/consultancy/contact" onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Contact' : 'Contact'}</span>
              </A>
            </li>
          </ul>
        </nav>
      </Show>

      <Show when={location.pathname.startsWith('/tools') && navigationVisible()}>
        <nav class="sub" style="transition: all 0.3s ease-in-out">
          <ul>
            <li>
              <A href="/tools" end onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Home' : 'Home'}</span>
              </A>
            </li>
            <li>
              <A href="/tools/reach" onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Bereik' : 'Reach'}</span>
              </A>
            </li>
            <li>
              <A href="/tools/docs" onClick={handleClick}>
                <span>{language() === 'nl-NL' ? 'Documentatie' : 'Docs'}</span>
              </A>
            </li>
          </ul>
        </nav>
      </Show>

      <style>{`
  nav {
    display: grid;
    grid-template-columns: 1fr;
    grid-column: 1/3;
  }

  nav.key {
    padding: 1em 1.4em 1em 1.4em;
    background-color: var(--ra-teal-light);
  }

  nav.sub {
    padding: 1em 1.4em 1em 1.4em;
    background-color: var(--ra-black-off-white);
  }

  ul {
    grid-column: 1/1;
    display: flex;
    flex-direction: column;
    gap: 1em;
    justify-content: flex-start;
    align-items: flex-start;
    flex-wrap: wrap;
  }

  .main-nav ul li:first-of-type {
    flex: 1 1 3rem;
    font-family: 'Trebuchet MS';
  }

  nav.key a.brand span.blue {
    color: var(--ra-white);
  }
  nav.key a span.green {
    color: var(--ra-white);
  }
  nav.key a span.red {
    color: var(--ra-white);
  }
  nav.key a,
  nav.key a:visited {
    color: var(--ra-grey-off-white);
  }
  nav.sub a,
  nav.sub a:visited {
    color: var(--ra-grey-light);
  }
  nav.key a:hover,
  nav.sub a:hover {
    color: var(--ra-blue);
  }
  nav.key a:hover span.blue {
    color: var(--ra-blue);
  }
  nav.key a:hover span.green {
    color: var(--ra-green);
  }
  nav.key a:hover span.red {
    color: var(--ra-red);
  }
  nav.key a.active span.blue {
    color: var(--ra-blue);
  }
  nav.key a.active span.green {
    color: var(--ra-green);
  }
  nav.key a.active span.red {
    color: var(--ra-red);
  }
  nav.sub a.active span {
    color: var(--ra-blue);
  }

  @media screen and (min-width: 760px) {
    nav {
      grid-template-columns: 1fr 4fr 1fr;
    }
    nav.key {
      padding: 2rem 1rem 2rem 1rem;
    }
    nav.sub {
      padding: 1rem 1rem 1rem 1rem;
    }
    ul {
      grid-column: 2/3;
      flex-direction: row;
      align-items: flex-start;
      gap: clamp(0.4em, 4vw, 9.6em);
    }
    nav.key ul {
      justify-content: space-evenly;
    }

    nav.key ul li:nth-of-type(1) {
      flex: 1 1 auto;
    }

    nav.sub ul {
      justify-content: center;
    }
  }
      `}</style>
    </>
  );
}

// imports/ui/components/Navigation.svelte
<script>
  // packages
  import {Route, active, router} from 'tinro';

  // components
  // import Select from '../components/reusable/Select.svelte';
  import LogoCommsWithAPlan from './reusable/LogoCommsWithAPlan.svelte';
  import LogoReachApp from './reusable/LogoReachApp.svelte';

  // modules
  import UiProvider from '../../both/uiProvider';

  // constants
  import {translations} from '../../../client/constants';
  import {home} from 'svelte-awesome/icons';

  // variables
  export let language;
  let thisUi = new UiProvider(translations, language);
</script>

<nav class="main-nav">
  <ul>
    <li>
      <a href={'/'} use:active>
        <LogoCommsWithAPlan size={'3.5rem'} colored={$router.url === '/'} />
      </a>
    </li>
    <li>
      <a href={'/plan/home'} use:active>
        <span class="brand blue">Comms</span>&nbsp;<span class="brand green">With&nbsp;A</span>&nbsp;<span
          class="brand red">Plan</span
        >
      </a>
    </li>
    <li>
      <a href={'/reach/home'} use:active>
        {thisUi.capitalizeAndSplit('reach')}
      </a>
    </li>
  </ul>
</nav>
{#if $router.url === '/'}
  <nav class="sub-nav" />
{/if}
{#if $router.url === path}
  <nav class="sub-nav">
    <ul>
      <li>
        <a href={'/commswithaplan/home'} use:active>
          <LogoCommsWithAPlan size={'2rem'} colored={$router.url === '/commswithaplan/home'} />
        </a>
      </li>
    </ul>
  </nav>
{/if}
{#if $router.url === path}
  <nav class="sub-nav">
    <ul>
      <li>
        <a href={'/reach/home'} use:active>
          <LogoReachApp size={'2rem'} colored={$router.url === '/reach/home'} />
        </a>
      </li>

      <li>
        <a href={'/reach/reachapp'} use:active>
          <span class="brand">ReachApp</span>
        </a>
      </li>
      <li>
        <a href={'/reach/download'} use:active>
          {thisUi.capitalizeAndSplit('download')}
        </a>
      </li>
      <li>
        <a href={'/reach/manual'} use:active>
          {thisUi.capitalizeAndSplit('manual')}
        </a>
      </li>
    </ul>
  </nav>
{/if}

<style>
  nav {
    display: flex;
    margin: 0;
    padding: 0 1em;
    width: 100%;
    font-size: 1.4rem;
    z-index: 999;
  }
  nav.main-nav {
    justify-content: space-between;
    background-color: var(--ra-teal-transparant);
    height: var(--ra-nav-main-height);
  }
  nav.sub-nav {
    justify-content: center;
    background-color: var(--ra-teal-light-transparant);
    height: var(--ra-nav-sub-height);
  }
  ul {
    display: flex;
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
  @media only screen and (max-width: 768px) {
    ul {
      flex-direction: column;
    }
  }

  a {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    padding: 0 1em;
    text-decoration: none;
  }

  /* :link */
  a:link {
    color: var(--ra-white);
  }
  /* :visited */
  a:visited {
    color: var(--ra-white);
  }
  /* :hover */
  a:hover {
    color: var(--ra-grey);
  }
  nav.main-nav a:hover {
    background-color: var(--ra-teal-light-transparant);
  }

  nav.sub-nav a:hover {
    background-color: var(--ra-white);
  }

  /* :active */
  a.active {
    color: var(--ra-blue);
  }
  ul:first-child a.active {
    background-color: transparent;
  }
  nav.main-nav a.active {
    background-color: var(--ra-teal-light-transparant);
  }
  nav.sub-nav a.active {
    background-color: var(--ra-white);
  }
  /* brand */
  span.brand {
    font-family: 'Trebuchet MS';
  }
  a.active span.blue {
    color: var(--ra-blue);
  }
  a.active span.green {
    color: var(--ra-green);
  }
  a.active span.red {
    color: var(--ra-red);
  }

  form {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-left: auto;
    margin-right: 1em;
  }
  label {
    color: var(--ra-white);
    padding: 0em 0.5em;
  }
</style>
