// imports/ui/components/legal/cookie/Cookie.svelte
<script lang="ts">
  // imports
  import PolicyArticle from '../PolicyArticle.svelte';
  import {language} from '../../../stores/utils';
  import {cookiePolicy} from '../../../stores/legal';

  // variables
  $: translatedCookiePolicy = $cookiePolicy.filter((item) => item.language === $language);
</script>

{#each translatedCookiePolicy as item}
  <PolicyArticle {item} />
{/each}

// imports/ui/components/legal/cookie/Cookie.tsx
import {For, createMemo} from 'solid-js';
import PolicyArticle from '../PolicyArticle';
import {language} from '../../../stores/utils';
import {cookiePolicy} from '../../../stores/legal';

export default function Cookie() {
  const translatedCookiePolicy = createMemo(() => 
    cookiePolicy().filter((item) => item.language === language())
  );

  return (
    <>
      <For each={translatedCookiePolicy()}>
        {(item) => <PolicyArticle item={item} />}
      </For>
    </>
  );
}
