// imports/ui/components/reusable/Modal.tsx
// imports
import { Show, JSX, createSignal } from 'solid-js';
import { faXmark } from '@fortawesome/free-solid-svg-icons';
import Fa from 'solid-fa';

type ModalProps = {
  title?: string;
  display: boolean;
  onClose?: () => void;
  children?: JSX.Element;
  footer?: JSX.Element;
};

export default function Modal(props: ModalProps) {
  const [disabled] = createSignal(false);

  return (
    <Show when={props.display}>
      <div
        class="backdrop"
        style={`display:${props.display ? 'flex' : 'none'}; transition: opacity 0.4s ease-in-out`}
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation();
        }}
        onKeyDown={(e) => {}}
        onKeyUp={(e) => {}}
        onKeyPress={(e) => {}}
      >
        <div class="modal">
          <menu>
            <button
              type="button"
              aria-roledescription="button"
              disabled={disabled()}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                props.onClose?.();
              }}
            >
              <Fa icon={faXmark} />
            </button>
          </menu>
          <header>
            <h3 class="modal__title">{props.title || 'modal_title'}</h3>
          </header>
          <div class="modal__body">{props.children}</div>
          <footer>{props.footer}</footer>
        </div>
        <style>{`
  div.backdrop {
    justify-content: center;
    align-items: center;
    height: 100%;
    width: 100%;
    position: fixed;
    top: 0em;
    left: 0em;
    background: rgba(0, 0, 0, 0.5);
    z-index: 100;
  }
  .modal {
    flex: 0 1 40rem;
    display: grid;
    grid-template-columns: 1fr;
    justify-content: space-evenly;
    align-items: center;
    margin: 1.4em;
    padding: 1.2em 1em 2em;
    font-size: 1em;
    background-color: var(--ra-white);
    border-radius: 0.6em;
  }
  menu {
    display: flex;
    justify-content: flex-end;
    width: 100%;
  }
  button {
    background-color: transparent;
    border-color: transparent;
    font-size: 1.5em;
    margin: 0 0.4em;
    cursor: pointer;
    border-radius: 5%;
    border: none;
  }

  button:hover {
    opacity: 0.7;
  }
  header {
    display: flex;
    justify-content: center;
    margin: 1em 0;
  }
  div.modal__body {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 1em 0;
  }
  footer {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 1em 0;
  }
        `}</style>
      </div>
    </Show>
  );
}

// imports/ui/reusable/Modal.svelte
<script lang="ts">
  // imports
  import {fade} from 'svelte/transition';
  import {createEventDispatcher} from 'svelte';
  import Fa from 'svelte-fa/src/fa.svelte';
  import {faXmark} from '@fortawesome/free-solid-svg-icons';

  // variables
  export let title: string;
  export let display: string = 'none';
  let dispatch = createEventDispatcher();
  let disabled = false;

  // functions
  function dismiss(event: MouseEvent | CustomEvent | KeyboardEvent): void {
    if (
      (event instanceof KeyboardEvent && event.key === 'Escape') ||
      event instanceof CustomEvent ||
      event instanceof MouseEvent
    ) {
      display = 'none';
      // 'destroyModal' gives opportunity to be specific if there are multiple modals
      dispatch('destroyModal');
    }
  }
</script>

<svelte:window on:keyup={dismiss} />
{#if display == 'flex'}
  <div
    class="backdrop"
    style="display:{display}"
    transition:fade={{delay: 0, duration: 400}}
    on:click|preventDefault|stopPropagation|self={dismiss}
  >
    <div class="modal">
      <menu>
        <button
          type="button"
          aria-roledescription="button"
          {disabled}
          on:click|stopPropagation|preventDefault={dismiss}
        >
          <Fa icon={faXmark} />
        </button>
      </menu>
      <header>
        <h3 class="modal__title">{title}</h3>
      </header>
      <div class="modal__body">
        <slot />
      </div>
      <footer>
        <slot name="modal__footer" />
      </footer>
    </div>
  </div>
{/if}

<style>
  div.backdrop {
    justify-content: center;
    align-items: center;
    /* height: 100%; */
    position: fixed;
    top: 0em;
    left: 0em;
    background: rgba(0, 0, 0, 0.5);
    z-index: 100;
  }
  .modal {
    flex: 0 1 40rem;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    align-items: center;
    margin: 1.4em;
    padding: 1.2em 1em 2em;
    font-size: 1em;
    background-color: var(--ra-white);
    border-radius: 0.6em;
  }
  menu {
    display: flex;
    justify-content: flex-end;
    width: 100%;
  }
  button {
    background-color: transparent;
    border-color: transparent;
    font-size: 1.5em;
    margin: 0 0.4em;
    cursor: pointer;
    border-radius: 5%;
    border: none;
  }

  button:hover {
    opacity: 0.7;
  }
  header {
    display: flex;
    justify-content: center;
    margin: 1em 0;
  }
  div.modal__body {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 1em 0;
  }
  footer {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 1em 0;
  }
</style>
