// imports/ui/components/consultancy/about/About.tsx
import {For, createMemo} from 'solid-js';
import BreadCrumbs from '../../reusable/BreadCrumbs';
import Card from '../../reusable/Card';
import {language} from '../../../stores/utils';
import {aboutItems} from '../../../stores/consultancy';
import createConverter from '/imports/ui/functions/convert';

export default function About() {
  const converter = createConverter();

  const expandedAboutItems = createMemo(() =>
    converter.expandItems(aboutItems(), language())
  );

  return (
    <>
      <header>
        <BreadCrumbs />
      </header>
      <section>
        <div class="about__flex">
          <For each={expandedAboutItems()}>
            {(item) => (
              <Card card={{fontSize: '0.9em'}}>{item.description}</Card>
            )}
          </For>
          <Card card={{fontSize: '0.9em'}}>
            <a href="https://www.linkedin.com/in/cbaarendse/">https://www.linkedin.com/in/cbaarendse/</a>
          </Card>
        </div>
        <style>{`
  .about__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2em;
  }

  .about__flex .card {
    flex: 1 1 32rem;
  }
        `}</style>
      </section>
    </>
  );
}

// imports/ui/main/consultancy/About.svelte
<script lang="ts">
  // imports
  import BreadCrumbs from '../../reusable/BreadCrumbs.svelte';
  import Card from '../../reusable/Card.svelte';
  import {language} from '../../stores/utils';
  import {aboutItems} from '../../stores/consultancy';

  // variables;
  $: translatedAboutItems = $aboutItems.filter((item) => item.language === $language);
</script>

<header>
  <BreadCrumbs breadCrumbs={['consultancy']} />
</header>
<section>
  <div class="about__flex">
    {#each translatedAboutItems as item}
      <Card card={{sizes: '1em'}}>{item.description}</Card>
    {/each}
    <Card card={{sizes: '1em'}}>
      <a href="https://www.linkedin.com/in/cbaarendse/"> https://www.linkedin.com/in/cbaarendse/ </a>
    </Card>
  </div>
</section>

<style>
  .about__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2rem;
  }

  .about__flex :global(.card) {
    flex: 1 1 320px;
  }
</style>
