// imports/ui/components/consultancy/contact/Contact.tsx
import {For, createMemo, Show} from 'solid-js';
import BreadCrumbs from '../../reusable/BreadCrumbs';
import Card from '../../reusable/Card';
import {language} from '../../../stores/utils';
import {contactItems} from '../../../stores/consultancy';
import createConverter from '/imports/ui/functions/convert';

export default function Contact() {
  const converter = createConverter();

  const expandedContactItems = createMemo(() =>
    converter.expandItems(contactItems(), language())
  );

  return (
    <>
      <BreadCrumbs />
      <section>
        <div class="contact__flex">
          <For each={expandedContactItems()}>
            {(item) => (
              <Card
                card={{
                  color: item.color,
                  title: item.displayName,
                  fontSize: '0.9em'
                }}
              >
                <address innerHTML={item.description?.split(', ').join('<br>')} />
              </Card>
            )}
          </For>
          <Card
            card={{
              title: 'LinkedIn',
              color: 'blue',
              fontSize: '1em',
              link: 'https://www.linkedin.com/in/cbaarendse/',
              action: 'Constantijn Baarendse'
            }}
          />
        </div>
        <h5>
          {language() === 'nl-NL'
            ? 'E-mail, bel, schrijf of stuur een bericht via LinkedIn.'
            : 'E-mail, call, write or send a message through LinkedIn.'}
        </h5>
        <style>{`
  h5 {
    color: var(--ra-red);
  }
  .contact__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2em;
  }

  .contact__flex .card {
    flex: 1 1 30rem;
  }
        `}</style>
      </section>
    </>
  );
}

// imports/ui/main/consultancy/Contact.svelte
<script lang="ts">
  // imports
  import Main from './layout/Main.svelte';
  import Header from './layout/Header.svelte';
  import Section from './layout/Section.svelte';
  import Brand from '../../reusable/Brand.svelte';
  import LogoCommsWithAPlan from '../../reusable/LogoCommsWithAPlan.svelte';
  import Card from '../../reusable/Card.svelte';
  import {language} from .../../stores/ui
  import {contactItems} from '../../stores/consultancy';
  $: translatedContactItems = $contactItems.filter((item) => item.language === $language);
</script>

<Main>
  <Section>
    <div class="contact__flex">
      <Header>
        <Brand
          brand={{
            color: 'var(--ra-blue)',
            fontSize: 'var(--ra-fs-2xl)',
            title: `Consultancy - ${$language === 'dutch' ? 'Contact' : 'Contact'}`
          }}
          ><LogoCommsWithAPlan
            logo={{
              fontSize: 'var(--ra-fs-5xl)',
              width: 'var(--ra-5xl)',
              height: 'var(--ra-5xl)',
              minWidth: 'var(--ra-5xl)',
              minHeight: 'var(--ra-fxl)',
              colored: true
            }}
          />
        </Brand>
      </Header>

      {#each translatedContactItems as item}
        <Card card={{color: 'blue', title: item.displayName}}>
          <address>
            {item.description}
          </address>
        </Card>
      {/each}
      <Card
        card={{title: 'LinkedIn', color: 'blue', link: 'https://www.linkedin.com/in/cbaarendse/', action: 'LinkedIn'}}
      >
        <address>
          <a href="https://www.linkedin.com/in/cbaarendse/"><b>In</b></a>
        </address>
      </Card>
    </div>
    <span
      >{#if $language == 'dutch'}
        Bel me of schrijf.
      {:else}
        Give me a call or write.
      {/if}
    </span>
  </Section>
</Main>

<style>
  span {
    color: var(--ra-red);
  }
  .contact__flex {
    display: flex;
    flex-wrap: wrap;
    gap: 2rem;
  }

  .contact__flex :global(header) {
    flex: 0 1 100%;
  }
  .contact__flex :global(.card) {
    flex: 1 1 320px;
  }
</style>
