// imports/ui/components/tools/docs/DocsChapter.tsx
import {For, Show} from 'solid-js';
import DocsParagraph from './DocsParagraph';
import type {Chapter} from '../../../../both/typings/types';

interface DocsChapterProps {
  chapter: Chapter;
}

export default function DocsChapter(props: DocsChapterProps) {
  return (
    <article>
      <h2>&sect;&nbsp;{props.chapter.displayName}</h2>
      <ul>
        <Show when={props.chapter.paragraphs}>
          <For each={props.chapter.paragraphs}>
            {(paragraph) => (
              <li>
                <DocsParagraph
                  subtitle={paragraph.displayName}
                  text={paragraph.description}
                  elaboration={paragraph.elaboration}
                />
              </li>
            )}
          </For>
        </Show>
      </ul>
      <Show when={props.chapter.imgFiles}>
        <For each={props.chapter.imgFiles}>
          {(imgFile) => (
            <picture>
              <img src={`/docs${imgFile}`} alt={props.chapter.displayName} />
            </picture>
          )}
        </For>
      </Show>
      <style>{`
  article,
  ul {
    display: flex;
    flex-wrap: wrap;
    gap: 0.8em;
  }
  h2 {
    margin: 0em 0em;
  }
  img {
    max-width: 30rem;
  }
      `}</style>
    </article>
  );
}

// imports/ui/main/tools/DocsChapter.svelte
<script lang="ts">
  // imports
  import DocsParagraph from './DocsParagraph.svelte';
  import type {Chapter} from '../../types/types';

  // exports
  export let chapter: Chapter;
</script>

<article>
  <h2>&sect;&nbsp;{chapter.displayName}</h2>
  <ul>
    {#if chapter.paragraphs}
      {#each chapter.paragraphs as paragraph}
        <li>
          <DocsParagraph
            subtitle={paragraph.displayName}
            text={paragraph.description}
            elaboration={paragraph.elaboration}
          />
        </li>
      {/each}
    {/if}
  </ul>
  {#if chapter.imgFiles}
    {#each chapter.imgFiles as imgFile}
      <picture>
        <img src="/docs{imgFile}" alt={chapter.displayName} />
      </picture>
    {/each}
  {/if}
</article>

<style>
  article {
    display: flex;
    flex-direction: column;
    gap: 1em;
  }
  h2 {
    margin: 0em 0em;
  }
  img {
    max-width: 30rem;
  }
</style>
