// imports/ui/components/tools/reach/GenderButton.tsx
import {createMemo} from 'solid-js';
import {faPerson, faPersonDress} from '@fortawesome/free-solid-svg-icons';
import Fa from 'solid-fa';
import {genders, marketData, useForResults} from '../../../stores/reach';

interface GenderButtonProps {
  onChangeGender: () => void;
}

export default function GenderButton(props: GenderButtonProps) {
  const gendersToWorkWith = createMemo(() => new Set(genders() ?? ['f', 'm', 'x']));
  const disabled = createMemo(() => !marketData() || useForResults() === 'formula');

  const toggleGenders = () => {
    let newGenders = new Set(gendersToWorkWith());
    
    if (newGenders.has('f') && newGenders.has('m') && newGenders.has('x')) {
      newGenders.delete('m');
      newGenders.delete('x');
    } else if (newGenders.has('f') && !newGenders.has('m') && !newGenders.has('x')) {
      newGenders.delete('f');
      newGenders.add('m');
    } else if (!newGenders.has('f') && newGenders.has('m') && !newGenders.has('x')) {
      newGenders.add('f');
    } else if (newGenders.has('f') && newGenders.has('m') && !newGenders.has('x')) {
      newGenders = new Set(['f', 'm', 'x']);
    } else if (!newGenders.has('f') && !newGenders.has('m') && !newGenders.has('x')) {
      newGenders = new Set(['f', 'm', 'x']);
    }
    
    genders.set(Array.from(newGenders));
    props.onChangeGender();
  };

  return (
    <fieldset>
      <button
        class="genders__toggle"
        type="button"
        aria-roledescription="button"
        disabled={disabled()}
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation();
          toggleGenders();
        }}
      >
        <Fa
          icon={faPersonDress}
          color={gendersToWorkWith().has('f') && !gendersToWorkWith().has('x') ? 'var(--ra-red)' : 'var(--ra-grey-light)'}
        />
        <Fa
          icon={faPerson}
          color={gendersToWorkWith().has('m') && !gendersToWorkWith().has('x') ? 'var(--ra-red)' : 'var(--ra-grey-light)'}
        />
      </button>
      <style>{`
  fieldset {
    display: grid;
    grid-template-columns: 1fr;
    gap: 0.8rem;
    padding: 0.1rem 0.6rem;
    border: solid 1px var(--ra-teal-light);
    background-color: transparent;
    border-radius: 3px;
    height: 100%;
  }
  button {
    display: flex;
    gap: 1.6rem;
    justify-content: center;
    align-items: center;
    font-size: 2.1rem;
    background: transparent;
    border: none;
    cursor: pointer;
  }
  button:hover {
    opacity: 0.7;
  }
      `}</style>
    </fieldset>
  );
}

// imports/ui/main/tools/GenderButton.svelte
<script lang="ts">
  // imports
  import {strategy} from '../../stores/tools';
  import Fa from 'svelte-fa/src/fa.svelte';
  import {faPerson, faPersonDress} from '@fortawesome/free-solid-svg-icons';
  // variables
  let disabled = false;

  // exports

  // functions
  const combineGenders = function () {
    console.log('genders in combineGenders()', $strategy.genders);
    if ($strategy.genders) {
      let f = $strategy.genders.f;
      let m = $strategy.genders.m;
      if (f == false && m == false) {
        $strategy.genders = {f: true, m: false, x: false};
      }
      if (f == true && m == false) {
        $strategy.genders = {f: false, m: true, x: false};
      }
      if (f == false && m == true) {
        $strategy.genders = {f: true, m: true, x: false};
      }
      if (f == true && m == true) {
        $strategy.genders = {f: false, m: false, x: false};
      }
    }
  };
</script>

<button
  class="genders__toggle"
  type="button"
  aria-roledescription="button"
  {disabled}
  on:click|preventDefault|stopPropagation={combineGenders}
>
  <Fa icon={faPersonDress} size="4rem" color={$strategy.genders?.f ? 'var(--ra-red)' : 'var(--ra-grey-light'} />
  <Fa icon={faPerson} size="4rem" color={$strategy.genders?.m ? 'var(--ra-red)' : 'var(--ra-grey-light'} />
</button>

<style>
  button {
    width: 3.7rem;
    height: 3.7rem;
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 0 0.4em;
    cursor: pointer;
    background-color: transparent;
    border-radius: 5%;
    border: none;
  }
</style>
