// imports/ui/components/app/App.tsx
// imports
import Top from '../header/Top';
import Navigation from '../header/Navigation';
import Routing from '../routing/Routing';
import Colofon from '../footer/Colofon';
import Consent from '../footer/Consent';
import { consentFooterVisible } from '../../stores/utils';

// Routing: Main content, based on chosen routes
export default function App() {
  // functions
  function toggleFooterConsentVisibility() {
    consentFooterVisible.set(!consentFooterVisible());
  }

  return (
    <>
      <header>
        <Top />
        <Navigation />
      </header>
      <main>
        <Routing />
      </main>
      <footer>
        <Colofon onClick={toggleFooterConsentVisibility} />
        <Consent />
      </footer>
    </>
  );
}

// imports/ui/app/App.svelte
<script lang="ts">
  // imports
  import Header from '../header/Header.svelte';
  import Routing from '../main/routing/Routing.svelte';
  import Footer from '../footer/Footer.svelte';
  import FooterConsent from '../footer/FooterConsent.svelte';
  import {consentFooterVisible} from '../stores/utils';

  // variables

  // functions
  function toggleFooterConsentVisibility() {
    $consentFooterVisible = $consentFooterVisible === false ? true : false;
  }
</script>

<!-- Everything happens in these 3 components. -->
<!-- Header: TopBar, Navigation -->
<!-- Routing: Main content, based on chosen routes, always wrapped in a <main>-tag   -->
<!-- Footer: contact, copyright and consent -->
<!-- FooterConsent: options for cookie consent to choose from for user -->
<Header />
<Routing />
<Footer on:clickedButton={toggleFooterConsentVisibility} />
<FooterConsent />
