// imports/ui/components/legal/termsandconditions/TermsAndConditions.tsx
import {For, createMemo} from 'solid-js';
import PolicyArticle from '../PolicyArticle';
import {language} from '../../../stores/utils';
import {termsAndConditions} from '../../../stores/legal';

export default function TermsAndConditions() {
  const translatedTermsAndConditions = createMemo(() => 
    termsAndConditions().filter((item) => item.language === language())
  );

  return (
    <>
      <For each={translatedTermsAndConditions()}>
        {(item) => <PolicyArticle item={item} />}
      </For>
    </>
  );
}

// imports/ui/main/legal/TermsAndConditions.svelte
<script lang="ts">
  // imports
  import PolicyArticle from './PolicyArticle.svelte';
  import {language} from '../../stores/utils';
  import {termsAndConditions} from '../../stores/legal';

  // variables
  $: translatedTermsAndsConditions = $termsAndConditions.filter((item) => item.language === $language);
</script>

{#each translatedTermsAndsConditions as item}
  <PolicyArticle {item} />
{/each}
