// imports/ui/components/legal/privacy/Privacy.svelte
<script lang="ts">
  // imports
  import PolicyArticle from '../PolicyArticle.svelte';
  import {language} from '../../../stores/utils';
  import {privacyPolicy} from '../../../stores/legal';

  // variables
  $: translatedPrivacyPolicy = $privacyPolicy.filter((item) => item.language === $language);
</script>

{#each translatedPrivacyPolicy as item}
  <PolicyArticle {item} />
{/each}

// imports/ui/components/legal/privacy/Privacy.tsx
import {For, createMemo} from 'solid-js';
import PolicyArticle from '../PolicyArticle';
import {language} from '../../../stores/utils';
import {privacyPolicy} from '../../../stores/legal';

export default function Privacy() {
  const translatedPrivacyPolicy = createMemo(() => 
    privacyPolicy().filter((item) => item.language === language())
  );

  return (
    <>
      <For each={translatedPrivacyPolicy()}>
        {(item) => <PolicyArticle item={item} />}
      </For>
    </>
  );
}
