// imports/ui/components/tools/docs/Docs.tsx
import {For, createMemo} from 'solid-js';
import BreadCrumbs from '../../reusable/BreadCrumbs';
import DocsChapter from './DocsChapter';
import {language} from '../../../stores/utils';
import {toolsDocumentationChapters} from '../../../stores/tools';

export default function Docs() {
  const translatedToolsDocumentationChapters = createMemo(() =>
    toolsDocumentationChapters().filter((chapter) => chapter.language === language())
  );

  return (
    <>
      <BreadCrumbs />
      <section>
        <div class="container">
          <nav>
            <ul>
              <For each={translatedToolsDocumentationChapters()}>
                {(chapter) => (
                  <li>
                    <a href={`#${chapter.name}`} data-tinro-ignore>
                      {chapter.displayName}
                    </a>
                  </li>
                )}
              </For>
            </ul>
          </nav>
          <div class="chapters">
            <ul>
              <For each={translatedToolsDocumentationChapters()}>
                {(chapter) => (
                  <li id={chapter.name}>
                    <DocsChapter chapter={chapter} />
                  </li>
                )}
              </For>
            </ul>
          </div>
          <style>{`
  .container {
    display: flex;
    margin: 0em auto;
  }

  nav {
    display: none;
  }

  div.chapters {
    padding: 0em 0em;
  }

  div.chapters ul {
    padding: 0em 0em;
  }

  div.chapters ul li {
    margin-bottom: 4em;
  }

  @media screen and (min-width: 768px) {
    .container {
      gap: 2em;
    }
    nav {
      display: block;
      flex: 1 1 25ch;
    }
    nav ul {
      display: flex;
      flex-direction: column;
      gap: 1em;
      position: sticky;
      top: 1rem;
    }
    div.chapters {
      flex: 1 1 auto;
    }
  }
          `}</style>
        </div>
      </section>
    </>
  );
}

// imports/ui/components/tools/docs/Docs.svelte
<script lang="ts">
  // imports
  import BreadCrumbs from '../../reusable/BreadCrumbs.svelte';
  import DocsChapter from './DocsChapter.svelte';
  import {language} from '../../../stores/utils';
  import {toolsDocumentationChapters} from '../../../stores/tools';

  // variables
  $: translatedToolsDocumentationChapters = $toolsDocumentationChapters.filter(
    (chapter) => chapter.language === $language
  );
</script>

<BreadCrumbs />
<section>
  <div class="container">
    <nav>
      <ul>
        {#each translatedToolsDocumentationChapters as chapter}
          <li>
            <a href="#{chapter.name}" data-tinro-ignore>{chapter.displayName}</a>
          </li>
        {/each}
      </ul>
    </nav>
    <div class="chapters">
      <ul>
        {#each translatedToolsDocumentationChapters as chapter}
          <li id={chapter.name}>
            <DocsChapter {chapter} />
          </li>
        {/each}
      </ul>
    </div>
  </div>
</section>

<style>
  .container {
    /* TODO: flex needed? */
    display: flex;
    margin: 0em auto;
  }

  nav {
    display: none;
  }

  div.chapters {
    padding: 0em 0em;
    overflow-y: scroll;
  }

  div.chapters ul {
    /* TODO: flex needed */
    display: flex;
    flex-wrap: wrap;
    gap: 1.8em;
  }

  @media screen and (min-width: 768px) {
    nav {
      display: block;
      flex: 0 0 25%;
      padding: 1em;
    }
    nav ul {
      display: flex;
      flex-wrap: wrap;
      gap: 1.6em;
      position: fixed;
    }

    nav ul li {
      flex-basis: 100%;
    }
    div.chapters {
      flex: 1 1 75%;
    }
  }
</style>
