// imports/ui/components/tools/schedule/Home.tsx
export default function Home() {
  return (
    <style>{`
  /* schedule */

  /* TODO: to be turned into grid, with fixed dimensions in var() delete this file, once css is placed in Svelte component */

  div.schedule-button-space {
    width: 2em;
    min-height: 1px;
  }

  div.schedule-preamble {
    min-height: 1px;
  }

  div.schedule-fixed-preamble {
    width: 0%;
    min-height: 1px;
  }
    `}</style>
  );
}

// imports/ui/main/schedule/Home.svelte
<script lang="ts">
</script>

<style>
  /* schedule */

  /* TODO: to be turned into grid, with fixed dimensions in var() delete this file, once css is placed in Svelte component */

  div.schedule-button-space {
    width: 2em;
    min-height: 1px;
  }

  div.schedule-preamble {
    min-height: 1px;
  }

  div.schedule-fixed-preamble {
    width: 0%;
    min-height: 1px;
  }
</style>
