// imports/ui/routing/Routing.svelte
<script>
  // packages
  import {Route, router} from 'tinro';

  // components
  import Home from '../../ui/main/home/Home.svelte';
  import ConsultancyHome from '../../ui/main/consultancy/Home.svelte';
  import Work from '../../ui/main/consultancy/Work.svelte';
  import About from '../../ui/main/consultancy/About.svelte';
  import Contact from '../../ui/main/consultancy/Contact.svelte';
  import ToolsHome from '../../ui/main/tools/Home.svelte';
  import Reach from '../../ui/main/tools/Reach.svelte';
  import Docs from '../main/tools/Docs.svelte';
  import NotFound from '../../ui/main/notfound/NotFound.svelte';
</script>

<Route path="/*">
  <Route path="/"><Home /></Route>
  <Route path="/consultancy/*">
    <Route path="/"><ConsultancyHome /></Route>
    <Route path="/work"><Work /></Route>
    <Route path="/about"><About /></Route>
    <Route path="/contact"><Contact /></Route>
  </Route>
  <Route path="/tools/*">
    <Route path="/"><ToolsHome /></Route>
    <Route path="/reach"><Reach /></Route>
    <Route path="/documentation"><Docs /></Route>
  </Route>
  <Route fallback><NotFound /></Route>
</Route>

// imports/ui/components/routing/Routing.tsx
// imports
import { Routes, Route } from '@solidjs/router';
import Home from '../home/Home';
import Consultancy from '../consultancy/home/Consultancy';
import Work from '../consultancy/work/Work';
import About from '../consultancy/about/About';
import Contact from '../consultancy/contact/Contact';
import Tools from '../tools/home/Tools';
import Reach from '../tools/reach/Reach';
import Strategies from '../tools/reach/Strategies';
import Docs from '../tools/docs/Docs';
import Legal from '../legal/Legal';
import User from '../user/User';
import LoginSignin from '../user/LoginSignin';
import NotFound from '../notfound/NotFound';

export default function Routing() {
  return (
    <Routes>
      <Route path="/" component={Home} />
      
      <Route path="/consultancy" component={Consultancy} />
      <Route path="/consultancy/work" component={Work} />
      <Route path="/consultancy/about" component={About} />
      <Route path="/consultancy/contact" component={Contact} />
      
      <Route path="/tools" component={Tools} />
      <Route path="/tools/reach" component={Reach} />
      <Route path="/tools/reach/strategies" component={Strategies} />
      <Route path="/tools/docs" component={Docs} />
      
      <Route path="/legal/*" component={Legal} />
      
      <Route path="/user/loginsignin" component={LoginSignin} />
      <Route path="/user/:username" component={User} />
      
      <Route path="/*" component={NotFound} />
    </Routes>
  );
}
