// imports/ui/components/routing/Routing.tsx
// imports
import { Routes, Route } from '@solidjs/router';
import Home from '../home/Home';
import Consultancy from '../consultancy/home/Consultancy';
import Work from '../consultancy/work/Work';
import About from '../consultancy/about/About';
import Contact from '../consultancy/contact/Contact';
import Tools from '../tools/home/Tools';
import Reach from '../tools/reach/Reach';
import Strategies from '../tools/reach/Strategies';
import Docs from '../tools/docs/Docs';
import Legal from '../legal/Legal';
import User from '../user/User';
import LoginSignin from '../user/LoginSignin';
import NotFound from '../notfound/NotFound';

export default function Routing() {
  return (
    <Routes>
      <Route path="/" component={Home} />
      
      <Route path="/consultancy" component={Consultancy} />
      <Route path="/consultancy/work" component={Work} />
      <Route path="/consultancy/about" component={About} />
      <Route path="/consultancy/contact" component={Contact} />
      
      <Route path="/tools" component={Tools} />
      <Route path="/tools/reach" component={Reach} />
      <Route path="/tools/reach/strategies" component={Strategies} />
      <Route path="/tools/docs" component={Docs} />
      
      <Route path="/legal/*" component={Legal} />
      
      <Route path="/user/loginsignin" component={LoginSignin} />
      <Route path="/user/:username" component={User} />
      
      <Route path="/*" component={NotFound} />
    </Routes>
  );
}

// imports/ui/components/routing/Routing.svelte
<script lang="ts">
  // imports
  import {Route} from 'tinro';
  import Home from '../home/Home.svelte';
  import User from '../user/User.svelte';
  import Consultancy from '../consultancy/home/Consultancy.svelte';
  import Work from '../consultancy/work/Work.svelte';
  import About from '../consultancy/about/About.svelte';
  import Contact from '../consultancy/contact/Contact.svelte';
  import Tools from '../tools/home/Tools.svelte';
  import Reach from '../tools/reach/Reach.svelte';
  import Strategies from '../tools/reach/Strategies.svelte';
  import Docs from '../tools/docs/Docs.svelte';
  import Legal from '../legal/Legal.svelte';
  import NotFound from '../notfound/NotFound.svelte';

  // variables

  // functions
</script>

<Route path="/*" breadcrumb="home">
  <Route path="/"><Home /></Route>
  <Route path="/consultancy/*" breadcrumb="consultancy">
    <Route path="/"><Consultancy /></Route>
    <Route path="/work" breadcrumb="work"><Work /></Route>
    <Route path="/about" breadcrumb="about"><About /></Route>
    <Route path="/contact" breadcrumb="contact"><Contact /></Route>
  </Route>
  <Route path="/tools/*" breadcrumb="tools">
    <Route path="/"><Tools /></Route>
    <Route path="/reach" breadcrumb="reach">
      <Reach />
    </Route>
    <Route path="/reach/strategies" breadcrumb="strategies"><Strategies /></Route>
    <Route path="/docs" breadcrumb="docs"><Docs /></Route>
  </Route>
  <Route path="/legal/*" breadcrumb="legal"><Legal /></Route>

  <Route path="/user" breadcrumb="loginsignin"><User /></Route>

  <Route fallback breadcrumb="notfound"><NotFound /></Route>
</Route>
