// imports/ui/components/legal/PolicyArticle.svelte
<script lang="ts">
  // imports
  import type {Article} from '../../../both/typings/types';

  // variables
  export let item: Article;
</script>

<article>
  <h3>{item.displayName}</h3>
  {#each item.paragraphs as paragraph}
    <p>
      <strong>{paragraph.displayName}</strong>
      {paragraph.description}
    </p>
  {/each}
</article>

<style>
  article {
    /* TODO: no flex or row */
    display: flex;
    flex-direction: column;
    gap: 1em;
  }
  h3 {
    margin: 0em;
  }
  p {
    margin: 0em;
  }
</style>

// imports/ui/components/legal/PolicyArticle.tsx
// imports
import { For, JSX } from 'solid-js';
import type { Article } from '../../../both/typings/types';

type PolicyArticleProps = {
  item: Article;
};

export default function PolicyArticle(props: PolicyArticleProps) {
  return (
    <article>
      <h3>{props.item.displayName}</h3>
      <For each={props.item.paragraphs}>
        {(paragraph) => (
          <p>
            <strong>{paragraph.displayName}</strong>
            {paragraph.description}
          </p>
        )}
      </For>
      <style>{`
  article {
    display: flex;
    flex-direction: column;
    gap: 1em;
  }
  h3 {
    margin: 0em;
  }
  p {
    margin: 0em;
  }
      `}</style>
    </article>
  );
}
