// imports/ui/reusable/Brand.svelte
<script lang="ts">
  // types
  import type {Brand} from '../types/types';

  // variables
  export let brand: Brand;
</script>

<div class="brand">
  <slot />
  <span style:font-size={brand.style.fontSize} style:color={brand.style.color}>
    {brand.title}
  </span>
</div>

<style>
  .brand {
    align-self: center;
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
    gap: 0.7em;
    align-items: center;
    font-family: 'Trebuchet MS';
  }
</style>

// imports/ui/components/reusable/Brand.tsx
// imports
import { JSX } from 'solid-js';
import type { Brand as BrandType } from '../../../both/typings/types';

type BrandProps = {
  brand: BrandType;
  children?: JSX.Element;
};

export default function Brand(props: BrandProps) {
  return (
    <div class="brand">
      {props.children}
      <span style={`font-size:${props.brand.fontSize}; font-color:${props.brand.color}`}>
        {props.brand.title}
      </span>
      <style>{`
  .brand {
    align-self: center;
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
    gap: 0.7em;
    align-items: center;
    font-family: 'Trebuchet MS';
  }
      `}</style>
    </div>
  );
}
