// imports/ui/components/reusable/CardCopy.svelte
<script lang="ts">
  // imports
  import Image from './CardImage.svelte';
  import Title from './CardTitle.svelte';
  import Body from './CardBody.svelte';
  import Action from './CardAction.svelte';
  import Footer from './CardFooter.svelte';
  // types

  // variables
  export let backgroundColor: CSSStyleDeclaration['backgroundColor'];
  export let color: CSSStyleDeclaration['color'];
  export let fontSize: CSSStyleDeclaration['fontSize'];
  const C = {Image, Title, Body, Action, Footer};
</script>

<article class="card" style="background-color:{backgroundColor}; font-color:{color}; font-size:{fontSize}">
  <slot {C} />
</article>

<style>
  article.card {
    display: flex;
    flex-wrap: wrap;
    gap: 0.8em;
    padding: 0.7em;
    box-shadow: 0.1em 0.1em 0.2em 0 rgba(0, 0, 0, 0.1);
  }
</style>

// imports/ui/components/reusable/CardCopy.tsx
import type {JSX} from 'solid-js';
import Image from './CardImage';
import Title from './CardTitle';
import Body from './CardBody';
import Action from './CardAction';
import Footer from './CardFooter';

interface CardCopyProps {
  backgroundColor: string;
  color: string;
  fontSize: string;
  children: (components: {Image: typeof Image; Title: typeof Title; Body: typeof Body; Action: typeof Action; Footer: typeof Footer}) => JSX.Element;
}

export default function CardCopy(props: CardCopyProps) {
  const C = {Image, Title, Body, Action, Footer};
  
  return (
    <article 
      class="card" 
      style={{
        'background-color': props.backgroundColor,
        'color': props.color,
        'font-size': props.fontSize
      }}
    >
      {props.children(C)}
    </article>
  );
}

const styles = `
  .card {
    display: flex;
    flex-wrap: wrap;
    flex-direction: column;
    border-radius: 0.5rem;
    padding: 1.5rem;
  }
`;
